language: python

python:
  - 2.7.14
  - 3.6
  - 3.7
  - 3.8

install:
  - echo 'Install dependencies' && make dependencies

before_script:
  - echo 'Run PyLint' && make lint

script:
  - echo 'Run coverage and tests' && make cov-tests

after_success:
  - echo 'Run coveralls' && coveralls
